galaxy_info:
  author: community
  role_name: k3s
  description: Create a k3s cluster.
  company: none
  license: Apache
  min_ansible_version: '2.1'

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all

  galaxy_tags: [kubernetes, k3s, cluster]

dependencies: []
